### ISSUE TITLE
Icinga priority based notification.

### ISSUE THREAD

**Issue by praveendcis** [Icinga/icinga2-notification-alertops#1]
@bobapple Hi I just want to send notifications to two different groups based on priority.

For example, if I have two groups set 1. icingaadmins and 2. icingatest. If some service fails icinga should first send a notification to "**icingatest**" and if no action is taken with three consecutive notifications. Then icinga should send a notification to  "**icingaadmins**"

Please, can you help me.

**Comment by bobapple** [comment]
Hi @praveendcis 

I think you're searching for notification escalations. The Icinga docs have an example for this, hope it helps: https://www.icinga.com/docs/icinga2/latest/doc/03-monitoring-basics/#notification-escalations

**Comment by dnsmichi** [comment]
Stop highlighting team members, and cross-posting questions. This is a gentle warning.

icinga/icinga2#6117
